version: '3.8'
services:
    api-service:
        build: ./
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8080:8080
        environment:
            PORT: 8080
            FLASK_DEBUG: 1
    db:
        platform: linux/x86_64
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dbdashboard
        ports:
            - "3307:3306"
        volumes:
            - my-db:/var/lib/mysql
volumes:
    my-db: