version: '3.8'
services:
    api-service:
        build: ./flask_web/
        volumes:
            - ./flask_web/:/usr/src/app/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1