version: '3.8'
services:
    api-service:
        build: ./
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8080:8080
        environment:
            PORT: 8080
            FLASK_DEBUG: 1
    postgres:
        platform: linux/x86_64
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: testuser
            POSTGRES_PASSWORD: testuser
            APP_DB_NAME: dbdashboard
        ports:
            - "5432:5432"
        volumes:
            - my-db:/var/lib/mysql
            - ./data:/docker-entrypoint-initdb.d
volumes:
    my-db:
    data: